trigger:
  branches:
    include:
    - master
    - beta/*
    - hotfix/*

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-variables
- group: blip-sdk-js-sonar-qube
- name: skipDecorator 
  value: true

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/fix/plugin-deploy-prod

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-sdk-js
    type: javascript
    to: semantic-release
    skipSast: true
    skipSonarBranch: true
    npmCmds:
    - 'npm ci'
    - 'npm run bundle'
