trigger:
- master

pool:
  vmImage: ubuntu-22.04

variables:
- group: npmjs-sample-variables
- group: blip-sdk-js-sonar-qube

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/latest

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-sdk-js
    type: javascript
    to: semantic-release
    npmCmds:
    - 'npm ci'
    - 'npm run bundle'
    - 'npm publish'

- task: Bash@3
  displayName: 'Exibir conteúdo do último log npm'
  inputs:
    targetType: 'inline'
    script: |
      LOG_DIR="/home/vsts/.npm/_logs"
      LAST_LOG=$(ls -t $LOG_DIR/*.log 2>/dev/null | head -n 1)
      if [ -f "$LAST_LOG" ]; then
        echo "Conteúdo do log encontrado em: $LAST_LOG"
        cat "$LAST_LOG"
      else
        echo "Nenhum arquivo de log encontrado em $LOG_DIR"
      fi
