trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-sample-variables
- group: blip-sdk-js-sonar-qube

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/latest

extends:
  template: template-pipeline.yml@templates    
  parameters:
    nodeVersion: 14.x
    packagename: blip-sdk-js
    type: javascript
    to: semantic-release
    npmCmds:
    - 'npm ci'
    - 'npm run bundle'
    - 'npm publish'
