name: Manually Publish

on: workflow_dispatch

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm i -g codecov
      - run: npm run lint
      - run: npm run test:single
      - run: npm run test:check-coverage
      - run: cat ./coverage/lcov.info | codecov
        env:
          CODECOV_TOKEN: ${{secrets.codecov_token}}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run bundle
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
